remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ![circle](https://github.com/dusty91487/dusty91487.gethub.io/assets/63760861/91947adb-936c-4000-b1e4-27210df274be) Dustin Thompson
